site_name: Flat Editor for Unity
site_description: Open-source UI/UX tools for Asset authors
site_author: Evil Wizard Studios
theme: 'material'
repo_name: 'GitHub'
repo_url: 'https://git.io/vVZdI'
extra:
  version: '0.1.2'
  logo: 'img/logo.png'
  author:
    github: 'evilwizardstudios'
    twitter: 'evilwizards'
  palette:
    primary: 'orange'
    accent: 'pink'
    code: 'pink'
  font:
    text: 'Lato'
    code: 'Source Code Pro'
pages:
  - Home: index.md
  - Getting Started: start.md
  - The Grid: grid.md
  - Glyphs & Typography: typography.md
  - Forms: forms.md
  - Panels & Alerts: panels.md
  - Buttons & Navigation: buttonsnavs.md
  - Unity Objects: objects.md
  - Customize: customize.md
  - Code: code.md
markdown_extensions:
  - admonition
  - codehilite(css_class=code)
